[package]
authors = ["The Rust Project Developers"]
name = "core"
version = "0.0.0"
build = "build.rs"

[lib]
name = "core"
path = "lib.rs"
test = false

[features]
disable_float = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
